### ISSUE TITLE
Support GoPro camera

### ISSUE THREAD

**Issue by dsmit** [openstreetcam/ios#13]
Support for GoPro camera's (maybe more than one?) so someone could mount a forward and backward viewing camera.

**Comment by bogdans-telenav** [comment]
@dsmit We will try to add support for GoPro cameras in the next release 1.4.2. The build will most probably be sent to iTunes the latest on 09.09.2016 but it will be available for users only after a couple of days. 
This is our plan but if things change i will keep you posted.

**Comment by dsmit** [comment]
No worries! We'll see!

**Comment by bogdans-telenav** [comment]
@dsmit we did not add the support for GoPro in version 1.4.2

**Comment by bogdans-telenav** [comment]
@dsmit we actually had to by a developer account for the GoPro integration and this was a painful process with the legal team and other issues. As far as i remember it took like 1 month since Sep 2 2016 and since then we are working on several other features. This will enter in our plan since we have this account payed for 1 year. I will update you when i restart the active work on this.

**Comment by habi** [comment]
Any update on this?
Mapillary has been doing this for a while (albeit buggy), it would be a great addition to OSC in my opinion.

**Comment by alexandrui-telenav** [comment]
Unfortunately GoPro [discontinued](https://www.programmableweb.com/news/%E2%80%8Bgopro-shutters-its-developer-program/brief/2018/01/22) their developer program. 

There is an unofficial [API](https://github.com/KonradIT/goprowifihack) on Github but as the repo states it, it's a hack. One can use the GoPro to record imagery and upload through the scripts but no support in the apps in sight.

**Comment by habi** [comment]
Thanks for clarifying this.

**Comment by amilopowers** [comment]
@alexandrui-telenav could you give a link to those scripts?

**Comment by alexandrui-telenav** [comment]
Sure, https://github.com/openstreetcam/upload-scripts

**Comment by kiang** [comment]
Just another vote to have GoPro support. When I trying to capture photos on riding bicycle, it's hard to get smooth result through camera of phone.
