### ISSUE TITLE
Crash during upload for iPhone 5C

### ISSUE THREAD

**Issue by teemsaj** [openstreetcam/ios#14]
This is on a cell networkless (WiFi only) iPhone 5C running the latest version of iOS and OpenStreetView

I managed to grab this using iOS Console: 

Sep  1 20:22:02 Azul SpringBoard[48] <Warning>: Application 'UIKitApplication:com.telenav.OpenStreetView[0xd8e8]' exited abnormally via signal.
Sep  1 20:22:02 Azul UserEventAgent[23] <Warning>: 2668369712834: id=com.telenav.OpenStreetView pid=455, state=0

What I noticed happening was it would upload but after a while the app would crash. However I didn't grab the crash log right then, I'm hoping crashalytics have sent my logs over to you.

Please let me know if I can be of further help.

**Comment by bogdans-telenav** [comment]
We have all the Crashlytics logs. In the latest build we fixed a problem on upload. Can you try with version 1.5.4, this will be available in iTunes next week. I will close now this bug. If you still experinence any problem after updating to version 1.5.4 please open a new issue.
