### ISSUE TITLE
Doesn't clean up storage after upload?

### ISSUE THREAD

**Issue by dsmit** [openstreetcam/ios#22]
Doesn't seem to clean up its storage after upload, which results in filling the phone up to the brim and
now unable to record.

**Comment by bogdans-telenav** [comment]
@dsmit for debugging purposes we added some logs, the log file is OSVLogs, you can always delete the log folder with iTunes. We will remove this logging but for now is helping us debug some of the remaining bugs. 
For the next version i will explicitly delete the folder upon update. Thanks for pointing this out.
I will close this when i will commit the code on git.

**Comment by ChaerilM** [comment]
what about some kind of 'debug mode' option in settings to enable it

**Comment by bogdans-telenav** [comment]
Sorry I made the changes for this a long time ago but forgot to close this.
