### ISSUE TITLE
Upload progress indicator does not work as expected... and acts weird…

### ISSUE THREAD

**Issue by trailblazr** [openstreetcam/ios#23]
I had around **100MB** of photos for a short track to upload. The upload progress indicator seems to not work correctly. It always fell back to around 1-2% when reaching 50-52% and seemed to start over endlessly. This is really weird behavior and I only let it continue hoping the developer had tested that app before a release. Otherwise my upload will now DDoS the OpenStreetView image processing servers with an endless loop of uploading. :)

Nevertheless it is a nice & fancy looking hipster progress control which looks smart. **haha**

I will look into the code later... maybe I can fix that thing myself. ;-)

**Comment by bogdans-telenav** [comment]
A update was made to the server and a log out and log in is required.
Sorry for the inconvenience.

**Comment by bogdans-telenav** [comment]
@trailblazr Please reply if it fixed the problem.

**Comment by trailblazr** [comment]
Yep, that did the trick. That "server-update" must have been 5 mins ago, haha. Yeah, but the upload **now works flawlessly**. Thanks!! See success screenshot at http://www.noxymo.com/filespublic/osv_progress.PNG

**Comment by bogdans-telenav** [comment]
thanks!
