### ISSUE TITLE
Wifi OBD no longer working

### ISSUE THREAD

**Issue by ghost** [openstreetcam/ios#26]
I own a Veepeak VP-01 Wi-fi OBD reader, purchased exclusively for use with OpenStreetCam. I used the app and OBD reader together for several months without issue, only to have the app stop detecting the reader for no apparent reason. I am still able to use other OBD diagnostics apps on my iPhone, but OSC no longer indicated that it has a connection with my OBD reader. This leads me to believe that the issue is with the OSC app itself. I have attempted to use the connect option in settings with no luck. 

App version 1.4.7
iPhone 6S Plus, iOS 10.1.1.

**Comment by bogdans-telenav** [comment]
Please check again with the lates version (2.0). We made some fixes for your problem awhile ago.
