### ISSUE TITLE
Login fails?

### ISSUE THREAD

**Issue by jbowkett84** [openstreetcam/ios#28]
I don't seem to be able to Login? I'm not sure if I am doing something wrong.

**Comment by bogdans-telenav** [comment]
@jbowkett84 can you please add some context: app version, device, login provider (google, facebook, OSM)

**Comment by jbowkett84** [comment]
Thanks for the message Bogdan, it's working now that I have tried it again this morning.

I'm on iOS, iPhone, login by OSM, version 1.5.3(1).

James

James Bowkett MSc FGS
+447870733284
jebowkett@gmail.com

**Comment by bogdans-telenav** [comment]
Thanks for your quick answer. I will close this now.
