### ISSUE TITLE
Uploads failing & stuck in a loop

### ISSUE THREAD

**Issue by minty** [openstreetcam/ios#29]
After a recent road trip, I've got 23GB of images to upload, across ~10 tracks.  iOS app, fully up to date.

I start to upload, it gets somewhere between 100-200MB, then the app crashes.  I restart, and it repeats this in an endless loop.  Every time, it says 23.01GB of data to upload, even after 10+ iterations of "upload 100-200MB, app crashes".

I've tried pausing/resuming.  I've tried stop/starting the upload.  I've tried killing the app and re-launching.  Same symptoms, and I still have 23.01GB of data to upload.

Also, there is a ~8000 image track in my profile that's been stuck in "processing" for a couple of days.  http://openstreetcam.org/details/426956/0  The summary at the top of my profile says "0 processing", but the track itself is still showing "processing" and isn't visible publically.

So I guess two questions:

(a) How can I get the upload to progress?

(b) How can I get that ~8000 image track to complete processing?

Thanks!

**Comment by minty** [comment]
ps. The app crashes frequently and regularly for me (both uploading and less often when recording), but normally if I restart it enough times, the total data to upload reduces on each restart attempt & it eventually completes uploading.

iphone 6, with 128GB capacity.

**Comment by bogdans-telenav** [comment]
Sorry for this @minty app version 1.5.5 (2) has a very ugly crash i will update the app ASAP.

**Comment by ghost** [comment]
awesome! thanks for such a fast reply :)

I'll await the app update and retry & confirm here.

any idea if that is also related to why http://openstreetcam.org/details/426956/0 is stuck in a "processing" state, or is that something else?

**Comment by bogdans-telenav** [comment]
@bigredconvert 
About the track, I just checked with the guy that is working on the "processing" part. Your track got stuck in processing. This week we made a big change on the "processing" so from now on your tracks should no longer get stuck. Currently he is working on something else but as soon as he will have some free time he will restart the processing for your track (basically the last 50 images are not processed so only those need processing).

**Comment by minty** [comment]
cool - that is some awesomely amazing great support - thanks again to all involved 👍

**Comment by bogdans-telenav** [comment]
We had the review from apple (so i could just on click release this new version) but currently my colleagues are in vacation so the testing was not made. This bug also was caused by this situation and i do not want to risk another big issue. If you would like i can send you a beta build that fixes this but i would need a email or some sort of contact or if you can not provide any contact info i will add a link from where you can download a build.

**Comment by minty** [comment]
Hi - I've (hopefully) sent you an email with contact details.  Happy to help (or wait).

**Comment by bogdans-telenav** [comment]
The new version is online 1.5.6.

**Comment by bigredconvert** [comment]
Thanks!

I upgraded, launched, went to Uploads.  Speed sat at 0KB/s for ~30 seconds, then the app crashed.

I launched again & went to upload, speed was ~300KB/sec, and after a few seconds the total amount of data to upload was shown as 23.01GB

I got beyond 50MB, then I got distracted, came back & the app had crashed.

I launched again & went to upload, speed was initially ~90KB/sec, increased to ~300 - but the total data to upload was still 23.01GB. 

I noticed that the total uploaded (beneath the big % figure) would occassionally bounce between ~30MB and ~50MB, sort of flickering.  The track uploading was 1/8 through-out.  A minute or two after, the speed dropped to 0KB/sec - the internet connection was still fine generally.  After a minute or two of showing 0KB/sec, the app crashed.

I launched again, went to upload - still showing 23.01GB.

I can confirm I am running build 1.5.7(1) after upgrading through the app store.

:(

**Comment by minty** [comment]
(sorry, deleted previous version of this comment as I used the wrong account)

Thanks!

I upgraded, launched, went to Uploads. Speed sat at 0KB/s for ~30 seconds, then the app crashed.

I launched again & went to upload, speed was ~300KB/sec, and after a few seconds the total amount of data to upload was shown as 23.01GB

I got beyond 50MB, then I got distracted, came back & the app had crashed.

I launched again & went to upload, speed was initially ~90KB/sec, increased to ~300 - but the total data to upload was still 23.01GB.

I noticed that the total uploaded (beneath the big % figure) would occassionally bounce between ~30MB and ~50MB, sort of flickering. The track uploading was 1/8 through-out. A minute or two after, the speed dropped to 0KB/sec - the internet connection was still fine generally. After a minute or two of showing 0KB/sec, the app crashed.

I launched again, went to upload - still showing 23.01GB.

I can confirm I am running build 1.5.7(1) after upgrading through the app store.

:(

**Comment by minty** [comment]
Another try:

Got to ~54MB uploaded, then the total uploaded (beneath the big %) reset to 0 and started counting up again.  Still on "uploading track 1/8" before during and after.

Got to 55MB uploaded, then the total uploaded reset to 0bytes and started counting up again.  Still on track 1/8.  This pattern repeated a 3rd time, and I got a video of it.

https://youtu.be/rG6oYj_HvY0

This pattern repeated twice more after I recorded the video (so 5 iterations of 0 to ~55MB, then reset to 0, all the time still on track 1/8).  Then the app crashed.

Went to upload again & it's still reporting 23.01GB to upload.  At this point, based on observing the progress meter it suggests I've uploaded at least 300MB using v1.5.7(1), so I conclude I'm still stuck in a loop I'm unable to get out of :(

**Comment by bogdans-telenav** [comment]
@minty Sorry for your inconvenience. Can you please use the Report Issue feature from Settings this uploads the local logs to our servers and I can see exactly what happens. Please write in the comment something  so i can find your Issue easy like: "iOS - Minty - Upload fail"

**Comment by minty** [comment]
@bogdans-telenav done, included your suggested string 👍

**Comment by bogdans-telenav** [comment]
@minty I've read the logs, looks like the server ID of a sequence is wrong and the server refuses your upload this makes the app retry and retry until it crashes. **IF there is no bug in the sistem** this can only happen if you started to upload a recording with a user and tried to continue the upload on a different user **Or there is a bug on our server.** We can not check right now the server part but if you can confirm that you used several users on your device then that is the problem and maybe we should prevent this from happening in the future by preventing the user to upload a recording and change the users until he finishes the upload for that recording. Please reply so we can find a solution to your problem.

**Comment by bogdans-telenav** [comment]
@minty we highly appreciate all your patience and help.

**Comment by minty** [comment]
i'm 99.9% certain i've only ever used a single user/login for openstreetmap / openstreetcam

i'm 100% positive it's been the same single user on this device since before the current 23GB for 8 tracks pending upload were recorded.

(unless someone was using my device without my knowledge, but i'm pretty sure that hasn't happened).

sorry :(

happy to help - thanks so much for all the support - i wouldn't be so fussed, but i want the points for that 23Gb ;)

**Comment by bogdans-telenav** [comment]
@minty I sent you a email for a special fix for you. Please confirm that you received it.

**Comment by minty** [comment]
Got it :)

Thanks for taking so much trouble over this - I'll have a go at uploading over the weekend

You're all awesome - hope you have a lovely weekend!
