### ISSUE TITLE
Unable to Upload Imagery Via Wifi

### ISSUE THREAD

**Issue by blacktygeo** [openstreetcam/ios#31]
**Phone:**
- iPhone 8 Plus
- Model MQ8G2LL/A
- iOS 11.3.1

When selecting the "Upload All" button under the Upload menu, I receive a warning stating "Please connect to a Wi-Fi or allow uploading on cellular data from settings." (see photo below).  However, I am connected a Wi-Fi network at my residence and the error continues to pop up.  I tried a number of settings below to see if the issue would go away.

By the way, I tried using the Report an Issue function in the Settings menu and that also failed, stating that I should connect to Wi-Fi.  Additionally, I can submit a separate issue for this but the Report a Problem text box should have autocorrect enabled and, if it fails to send, should not erase the statement in the text box.

**Troubleshooting:**
- Tried loading websites on iOS Safari browser with no issues
- Disconnected from my 5ghz Wi-Fi network and connected to the 2.4ghz version
- Deactivated cellular data
- Restarted the OpenStreetCam app
- Restarted the phone

**Photo:**
![img_0376](https://user-images.githubusercontent.com/16174355/40625802-625abf3c-6269-11e8-9b35-998e7512a13a.PNG)

**Comment by blacktygeo** [comment]
Just an additional note, but I'm still getting the error on my Wi-Fi network at my residence but I was allowed to start uploading on my Wi-Fi at work.  I'm trying to figure out what is different to prevent the app from wanting to upload anything on my network at home since (with Cellular data turned off) I can still use Safari, my mail app, and others like normal while connected to Wi-Fi at home.

**Comment by ciprianh-telenav** [comment]
@blacktygeo, do you still face this issue on the latest version?
