### ISSUE TITLE
Blinking icons on the map

### ISSUE THREAD

**Issue by pcmill** [openstreetcam/ios#32]
When I am looking around the map I see the following:

[GIF](https://i.imgur.com/uuIEC7c.gif)

The blinking icons continue throughout the usage of the map. The phone I am using is an iPhone 7 Plus running iOS 11.4. While it does not affect for example recording streets, it is kind of annoying.

**Comment by habi** [comment]
I see the same: https://www.youtube.com/watch?v=z_0tZH5AhTY

iOS 12.0 (16A5327f) (public beta preview) on an iPhone SE (Model MLM62FD/A)

**Comment by ciprianh-telenav** [comment]
Pieter, David, this will be fixed in the next version which will be released by next week. Thank you!
