### ISSUE TITLE
Upload Resets 

### ISSUE THREAD

**Issue by OttoROSM** [openstreetcam/ios#36]
Since Saturday June 8th at around noon CET the upload of tracks keeps resetting after the metadata upload. At first I thought one of the tracks were corrupted, so I deleted them, but a new track has the same issue, so I reinstalled the app. This too kept the issue alive. 

I tried various wifi and cellular connections which did not make a change. Currently a 4 GB track is sitting on my device, which resets as soon as 11 MB is reached. Previous updates yesterday reached ~46MB before resetting (hence my suspect is the metadata). 

Then I tried to upload a crash report through the app, which upload failed as well, so now I am thinking it is the server side which keeps resetting the connection for some reason. 

I thought maybe it is because I crossed the German border, as the latest upload is from NL, but other apps (amazon foto, Google foto, Netflix etc...) work fine, both upload and download. And OSC worked fine in Germany in the past.

**Comment by OttoROSM** [comment]
And tonight it worked again. 
Incident solved, but no idea what the cause was.

**Comment by joeybab3** [comment]
I found this to happen occasionally as well, leaving it open for an hour or two lead to it uploading eventually. I don’t know what causes it and can’t figure out why it fixes but even changing connections and going to cellular doesn’t work.

**Comment by mirunac-telenav** [comment]
@OttoROSM - an unfortunate storage downtime occurred and it took a while to get it resolved. Everything is up and running now.
