### ISSUE TITLE
Point breakdown no longer able to be opened on app

### ISSUE THREAD

**Issue by joeybab3** [openstreetcam/ios#38]
I can no longer view the point breakdown on the IOS app by clicking on drives, not sure if this was intentionally removed but the only way to access it now is by going on the website.

**Comment by chip-grab** [comment]
@joeybab3, points breakdown is available on Track Preview screen by tapping on `Points ?` area
![OSC_TrackPreview_Details](https://user-images.githubusercontent.com/55801241/80286380-bea83d00-8733-11ea-9766-791cc3d0b2f6.jpeg)

**Comment by joeybab3** [comment]
@chip-grab thank you for the response, this issue is almost a year old and I believe that it indeed has been fixed in this time.
