### ISSUE TITLE
Compensate for camera tilt

### ISSUE THREAD

**Issue by brawer** [openstreetcam/ios#41]
Could the app compensate for camera tilt by rotating images? The app already knows the device tilt (and displays it on screen); perhaps it could compensate for that tilt by rotating the images at recording time, or maybe before uploading. This would be especially useful for pedestrians, since it’s difficult to hold a phone steady while walking.

**Comment by salabogdan** [comment]
Interesting idea but this would require some post processing on the backend side. Still I don't think it would look very well on the web UI.
