### ISSUE TITLE
All content lost.

### ISSUE THREAD

**Issue by Esmala** [openstreetcam/ios#42]
When I use high resolution (12mpix) or disrupt upload (lock phone or use stop button), it appears the upload is complete or continuing, but all content is actually gone, and will not appear to the map page even after a delay. It is not in the phone memory either. 

iOS version: 13.5.1

**Comment by salabogdan** [comment]
Hi, sorry for the late responses here, we have recently fixed a similar issue in release 4.9.1. Thanks to one of our community reports.
