### ISSUE TITLE
Map mode issues with panning / following

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/ios#44]
Picking up OpenStreetC...Kartaview for the first time in a while. Nice work on the new web site.

Using the latest App Store iOS version on an iPhone 12. I'll file separate issues for the few small issues / feature bumps I see. This one is about map browsing in the app. 

* When in Map mode, if I pan the map, it pans back to my current location, making it impossible to explore the map on mobile. 
* When in recording mode having the map as the main feature and the camera in the PiP window, when I pan / zoom the map there does not seem to be a way to put the map back in 'follow' mode. Use case for this is when I am stopped at a light, I want to see which streets ahead of me may not have been captured yet, but then when I start driving again, I want the map to follow my movement again.

**Comment by salabogdan** [comment]
hey @mvexel i am really happy to see you are back! We will address as soon as possible. I will add any new updates here.

**Comment by salabogdan** [comment]
Sorry, I forgot to reply here but this was fixed more than a year ago.
