### ISSUE TITLE
Upload stuck

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/ios#47]
My latest tracks won't finish uploading. The upload starts, uploads about 19MB, then the counter resets back to 0, and this repeats forever.

**Comment by Lining-Grab** [comment]
Hi, mvexel, may I know when did you start uploading?

**Comment by mvexel** [comment]
Tracks recorded on Dec 29 so probably on that day or the day after? Every time I try again is gives the same issue.

**Comment by lklepner** [comment]
I've also become stuck on the upload stage - 

https://user-images.githubusercontent.com/110027/157921300-0fdb9345-6c03-4e54-9e5c-6da191e0b9bc.MP4

**Comment by salabogdan** [comment]
this was fixed
