### ISSUE TITLE
Upload keeps restarting

### ISSUE THREAD

**Issue by joeybab3** [openstreetcam/ios#48]
I have an upload from an iPhone 7+ that keeps restarting when it hits 24.4mb and goes back to 0. it won't progress any further than this and new tracks that are recorded upload fine but an older track doesn't upload because it was recorded before the one that fails to upload.

**Comment by salabogdan** [comment]
Hi, sorry for the late response, we have recently fixed a similar issue in version 4.9.1 thanks to one of our community reports.
