### ISSUE TITLE
App keeps crashing when opened

### ISSUE THREAD

**Issue by joeybab3** [openstreetcam/ios#49]
When opening the app, I'm now met with "kartaview closed while uploading your tracks, continue uploading?" and then half a second later the app crashes. I can press yes or no at that time and it will still crash.

**Comment by salabogdan** [comment]
We are preparing an app update to address several major issues. One of the pain-points that will be address is the improvement of our crash reporting system, unfortunately for our latest release we can only blind fix your issue.

**Comment by salabogdan** [comment]
this should be fixed now
