### ISSUE TITLE
Be able to extract images locally

### ISSUE THREAD

**Issue by Zlitus** [openstreetcam/ios#51]
Hello,

I used to works with Mapillary, but unfortunately I switched from Android to an iPhone and now the mapillary application crash all the time. So I searched alternatives, and I found Kartaview and it's great.

Now, on Android with Mapillary, I was able to see all my pictures locally on my phone from my “Files” application, copy them to my compuer, remove some of them with are bad, etc. I didn't find any way in Kartaview for iOS to do the same. Would it be possible?
Ideally, I would like to retrieve the original HEIC files, but JPEG with metadata would be good too.

**Comment by salabogdan** [comment]
@Zlitus it is possible to get videos and if you want to see images you need to split videos into JPEGs using FFMP application.  Also in order to get lat long in JPEG metadata you would need to change a bit the "upload_scripts" repo or report a improvement which I would gladly help to implement.
