### ISSUE TITLE
Buttons off center

### ISSUE THREAD

**Issue by teemsaj** [openstreetcam/ios#6]
The screenshot better shows what I mean. https://imgur.com/a/omWbY

**Comment by teemsaj** [comment]
Last screenshot was an iPhone 6, this was on a 5C

https://imgur.com/a/qGNO5

**Comment by bogdans-telenav** [comment]
@teemsaj  Thanks for reporting.
Until now our focus was on devices with larger screen. We will work as soon as possible on improving the experience on devices with 4 inch screens.

**Comment by teemsaj** [comment]
@bogdans-telenav

This is on both the 5C and 6. I understand why there's extra space, but there must be a more graceful way of going about this.

**Comment by bogdans-telenav** [comment]
i am closing this with wont fix, this is the current design. In the next screen redesign we will take this into account.
