### ISSUE TITLE
No photos taken without cell network 

### ISSUE THREAD

**Issue by teemsaj** [openstreetcam/ios#9]
This app doesn't seem to record photos if the iPhone is not connected to a cell network. Doesn't feel like this app should require network connectivity. As long as GPS still functions, right?

**Comment by bogdans-telenav** [comment]
@teemsaj 
The app should record photos as long as you **start** the recording **with GPS**, if the app does not have GPS access it will prompt you and ask for GPS access. It does not use any cell network. 
Can you exactly describe your the use case?

**Comment by teemsaj** [comment]
I want to dedicate the 5C to do most of the photo recording, rather than my primary iPhone 6. It has to cell network capbility, but it does have GPS. That being said, on one of my runs today, it was not taking any photos at all. I'll try it again later today.

**Comment by taypo** [comment]
It may not be related to the cell network. I have iphone 5 with the cell nw and the app does not record anything either. I do hear the photo taking sound, but the count and distance does not update and when I finish the recording nothing gets uploaded.

**Comment by teemsaj** [comment]
Tried it again today, same deal.

**Comment by bogdans-telenav** [comment]
@teemsaj fixed it, in the next version will work. The problem was with the resolution of the video file resulting from your recording. iPhone 5C (have to check for other iPhone models, 5, 5S, 4S) can not make recordings with resolution larger then 2 MP. The sound is present because we make photos but because of the current settings we can not save them in videos, so you make photos but you don't actually record anything.

**Comment by bogdans-telenav** [comment]
We will upload tomorrow the new version to iTunes. This version will fix this issue.

**Comment by bogdans-telenav** [comment]
Uploaded the app to iTunes. I will close this.

**Comment by bogdans-telenav** [comment]
@teemsaj Can you please try to see if it works?

**Comment by taypo** [comment]
Recording works for me now. (iPhone5)

Cheers

31 Ağu 2016 tarihinde 11:59 saatinde, Bogdan Sala notifications@github.com şunları yazdı:

**Comment by bogdans-telenav** [comment]
@taypo thanks!

**Comment by teemsaj** [comment]
@bogdans-telenav Can confirm, working on iPhone 5C.

**Comment by bogdans-telenav** [comment]
@teemsaj Great!
Thanks guys! We really appreciate that you are active in helping us improve this project!
